name: medicare
description: A health based application to manage prescription
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  get_it: ^7.6.4
  shared_preferences: ^2.2.2
  event_bus: ^2.0.0
  flutter_bloc: ^8.1.3
  firebase_core: ^2.21.0
  logger: ^2.0.2+1
  firebase_auth: ^4.12.1
  get_storage: ^2.1.1
  go_router: ^12.0.1
  freezed_annotation: ^2.4.1
  google_sign_in: ^6.1.5
  lottie: ^2.6.0
  flutter_svg: ^2.0.9
  tflite_flutter: ^0.10.3
  image_picker: ^1.0.4
  flutter_native_image: ^0.0.6+1
  tflite_flutter_helper_plus: ^0.0.2
  google_mlkit_text_recognition: ^0.11.0
  camera: ^0.10.5+5
  font_awesome_flutter: ^10.6.0
  cloud_firestore: ^4.12.2
  dotted_decoration: ^2.0.0
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  rest_client: ^2.2.3+7
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  mime: ^1.0.4
  google_vision: ^1.0.6+4
  crypto_keys: ^0.3.0+1
  jose: ^0.3.4
  flutter_local_notifications: ^16.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.3

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/
    - assets/font/
    - assets/svg/
    - assets/raw/
    - assets/secrets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
