// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm1dZFE4AtVHfXuFY8KFRJ3RWA-saDIeU',
    appId: '1:606675885939:android:8c3381ba5790cb97a66f06',
    messagingSenderId: '606675885939',
    projectId: 'medicare-flutter',
    storageBucket: 'medicare-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSb2xe-k5pysUfdModHtfuaOwIxSamUHU',
    appId: '1:606675885939:ios:92e5f692e09084b5a66f06',
    messagingSenderId: '606675885939',
    projectId: 'medicare-flutter',
    storageBucket: 'medicare-flutter.appspot.com',
    androidClientId: '606675885939-hcli1k3kdvnk8bkm7c7634usrhbqoimh.apps.googleusercontent.com',
    iosClientId: '606675885939-5med1dti0q4vv53jq2dtckagsvilr9hg.apps.googleusercontent.com',
    iosBundleId: 'io.github.dracula101.medicare',
  );
}
